services:
  postgis:
    image: postgis/postgis
    container_name: postgiscontainer
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - postgres-network
    restart: unless-stopped

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmincontainer
    ports:
      - "15432:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=nacional@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    networks:
      - postgres-network
    restart: unless-stopped

  redis:
    image: redis/redis-stack
    container_name: rediscontainer
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-volumes:/data
    networks:
      - postgres-network
    
networks:
  postgres-network:
    driver: bridge

volumes:
  redis-volumes: