version: '3'

services:
  postgis:
    image: postgis/postgis
    container_name: postgis-container-nacional
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - postgres-network
    restart: unless-stopped

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin-container-nacional
    ports:
      - "15432:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=nacional@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    networks:
      - postgres-network
    restart: unless-stopped

networks:
  postgres-network:
    driver: bridge
